config/urls.py
from django.contrib import admin
from django.urls import path,include

#from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/',include('pybo.urls'),name='pybo'),

]

pybo/urls.py
from django.urls import path

from . import views
app_name = 'pybo'
urlpatterns = [
    path("", views.index,name='index'),
    path("<int:question_id>/", views.detail,name="detail"),
]

pybo/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
#from django.http import HttpResponse

from .models import Question


def index(request):
    question_list=Question.objects.order_by('-create_date')
    context={'question_list':question_list}
    return render(request,'pybo/question_list.html',context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/pybo/question_detail.html
<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>

templates/pybo/question_list.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
    <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}